drop database if exists GENERADORBD;
create database GENERADORBD;

use GENERADORBD;



drop table if exists nombres;

create table nombres(
id_nombre int primary key auto_increment,
nombre varchar(200) not null
)engine=innodb;

insert into nombres (nombre) values
("Aaron"),
("Zuzen"),
("Zuriko"),
("Zuri"),
("Zumarraga"),
("Zumar"),
("Zuhaitz"),
("Zorba"),
("Zora"),
("Zoilo"),
("Zoil"),
("Zoello"),
("Zoe"),
("Zir"),
("Zinaida"),
("Zigor"),
("Zeva"),
("Zeus"),
("Zettie"),
("Zeth"),
("Zeruko"),
("Zeru"),
("Zero"),
("Zernin"),
("Zera"),
("Zenos"),
("Zenobio"),
("Zenobia"),
("Zeno"),
("Zenia"),
("Zenaide"),
("Zena"),
("Zelotes"),
("Zelma"),
("Zelinda"),
("Zelig"),
("Zelia"),
("Zeledon"),
("Zelda"),
("Zefirino"),
("Zebina"),
("Zayed"),
("Zarek"),
("Zara"),
("Zanthe"),
("Zanita"),
("Zandra"),
("Zander"),
("Zale"),
("Zako"),
("Zajaruyya"),
("Zaida"),
("Zadornin"),
("Zado"),
("Zac"),
("Ywenn"),
("Ywen"),
("Yvonne"),
("Yvonette"),
("Yvon"),
("Yvette"),
("Yves"),
("Yveline"),
("Yvan"),
("Yvaine"),
("Yusuf"),
("Yuri"),
("Yunus"),
("Yuhannà"),
("Ysatis"),
("Youri"),
("Yoshio"),
("Yonde"),
("Yonda"),
("Yonathan"),
("Yoine"),
("Yohann"),
("Yohan"),
("Yoann"),
("Yasmine"),
("Yannis"),
("Yannick"),
("Yanni"),
("Yannel"),
("Yanis"),
("Yan"),
("Yalena"),
("Yale"),
("Yale"),
("Yaiza"),
("Yahya"),
("Yago"),
("Yaelle"),
("Xylona"),
("Xylon"),
("Xylina"),
("Xylia"),
("Xusto"),
("Xusta"),
("Xurxo"),
("Xulio"),
("Xulia"),
("Xudas"),
("Xosefina"),
("Xosefa"),
("Xorxe"),
("Xoel"),
("Xob"),
("Xoana"),
("Xoan"),
("Xise"),
("Ximun"),
("Ximena"),
("Xildas"),
("Xilda"),
("Xerome"),
("Xermán"),
("Xerardo"),
("Xenxo"),
("Xenoveva"),
("Xenos"),
("Xenophon"),
("Xenobia"),
("Xenia"),
("Xeneroso"),
("Xenerosa"),
("Xenaro"),
("Xena"),
("Xema"),
("Xefe"),
("Xarles"),
("Xaquelina"),
("Xanti"),
("Xanthus"),
("Xanthe"),
("Xantalen"),
("Xandy"),
("Xandra"),
("Xalbador"),
("Xaime"),
("Xacobo"),
("Xabier"),
("Xabier"),
("Xabat"),
("Wolf"),
("Wittono"),
("Wilson"),
("Willy"),
("Williams"),
("William"),
("Willem"),
("Will"),
("Wilfried"),
("Wilfrid"),
("Wilfredo"),
("Wilbero"),
("Wesly"),
("Wesley"),
("Wes"),
("Werner"),
("Wendy"),
("Wendell"),
("Wayne"),
("Wassi"),
("Warroo"),
("Warner"),
("Ward"),
("Wanda"),
("Walter"),
("Walce"),
("Volker"),
("Voleta"),
("Vivien"),
("Viviane"),
("Viviana"),
("Viveka"),
("Vittorio"),
("Vitoriano"),
("Vincent"),
("Vince"),
("Vilhelm"),
("Vidal"),
("Vid"),
("Victoro"),
("Victoria"),
("Victor"),
("Victoire"),
("Vicky"),
("Vicki"),
("Vicenzo"),
("Vicente"),
("Vicent"),
("Venance"),
("Velko"),
("Vekosv"),
("Veikko"),
("Vd"),
("Vay"),
("Vasilos"),
("Vasilis"),
("Vasilios"),
("Vasiliki"),
("Varick"),
("Varian"),
("Varden"),
("Vara"),
("Vanyo"),
("Vanio"),
("Vanessa"),
("Vamano"),
("Valence"),
("Vaina"),
("Vail"),
("Vachel"),
("Uzuri"),
("Uzuri"),
("Uzeil"),
("Uyendo"),
("Uxío"),
("Uxía"),
("Utu"),
("Utba"),
("Uta"),
("Ushnisha"),
("Usenko"),
("Urvan"),
("Urtzi"),
("Urtzi"),
("Úrsu"),
("Ursino"),
("Ursa"),
("Urritz"),
("Urre"),
("Urraca"),
("Urko"),
("Urki"),
("Uric"),
("Ulva"),
("Ulrika"),
("Ulrico"),
("Ulbrecht"),
("Uillioc"),
("Uhin"),
("Ugutz"),
("Ugo"),
("Ugaitz"),
("Uffo"),
("Udolfo"),
("Ubayy"),
("Ubayda"),
("U"),
("Txeru"),
("Txerran"),
("Treena"),
("Tracy"),
("Toumas"),
("Torrance"),
("Tori"),
("Tony"),
("Tom"),
("Todor"),
("Tod"),
("Tiffany"),
("Tienette"),
("Tidian"),
("Tibalt"),
("Tibalt"),
("Tiara"),
("Thyra"),
("Thyne"),
("Thorald"),
("Thomasa"),
("Thomas"),
("Theodora"),
("Thâbet"),
("Tevaite"),
("Teva"),
("Tessa"),
("Tess"),
("Tamara"),
("Tamara"),
("Talos"),
("Talia"),
("Stévina"),
("Stevie"),
("Stevens"),
("Steven"),
("Sofia"),
("Socrates"),
("Socrate"),
("Shelley"),
("Shelby"),
("Shei"),
("Sereno"),
("Sérèna"),
("Serena"),
("Serafín"),
("Rui"),
("Ruggiero"),
("Rufina"),
("Rond"),
("Roi"),
("Rogerio"),
("Roger"),
("Rogan"),
("Perrando"),
("Perpetua"),
("Pero"),
("Perline"),
("Peregrina"),
("Pere"),
("Otis"),
("Oliver"),
("Norbert"),
("Myrtille"),
("Myron"),
("Myriam"),
("Melody"),
("Melodia"),
("Melita"),
("Mélandre"),
("Mela"),
("Mateus"),
("Mateu"),
("Lewis"),
("Kurt"),
("Kurao"),
("Kristy"),
("Kristine"),
("Kristina"),
("Kevin"),
("Ketty"),
("June"),
("Joana"),
("Joan"),
("Joachim"),
("Jinny"),
("Isaura"),
("Isana"),
("Isana"),
("Isaías"),
("Isadora"),
("Isabelle"),
("Igone"),
("Igoa"),
("Igoa"),
("Ignazio"),
("Hollis"),
("Hoki"),
("Hodeiza"),
("Gullo"),
("Guisto"),
("Garin"),
("Garibaldo"),
("Gares"),
("Gares"),
("Gardotza"),
("Garden"),
("Florencia"),
("Federico"),
("Fede"),
("Evander"),
("Este"),
("Elvin"),
("Eluska"),
("Edwina"),
("Edwin"),
("Edwige"),
("Edward"),
("Eduvixes"),
("Edurtzeta"),
("Domingo"),
("Diana"),
("Danielle"),
("Cristal"),
("Cressida"),
("Cre"),
("Cassandra"),
("Caitlin"),
("Caitan"),
("Cailin"),
("Caden"),
("Berart"),
("Berart"),
("Bérangère"),
("Beppo"),
("Aude"),
("Arthur"),
("Aretina"),
("Aretha"),
("Ares"),
("Ange"),
("Ademaro"),
("Adelphos"),
("Abdel"),
("Abbud"),
("Abbas"),
("Abban"),
("Abadie"),
("Abad");





drop table if exists apellidos;

create table apellidos(
id_apellido int primary key auto_increment,
apellido varchar(200) not null
)engine=innodb;


insert into apellidos (apellido) values

("Abrilver"),
("Carmonaver"),
("Careagaver"),
("Cardonaver"),
("Cárcamover"),
("Carbonéver"),
("Capmanyver"),
("Cansinover"),
("CánovasverMurcia"),
("Cancinover"),
("Campanaver"),
("Camachover"),
("Calzadaver"),
("Calelver"),
("Callejaver"),
("Calderaver"),
("Cadalsover"),
("Cáceresver"),
("Cabreraver"),
("Cabezónver"),
("Cabezasver"),
("Cabellover"),
("Cabañasver"),
("Cabalver"),
("Burrellver"),
("Brionesver"),
("Brandisver"),
("Borrellver"),
("Borrellver"),
("Borrajover"),
("Bolívarver"),
("Bellocsver"),
("Bellochver"),
("Belleraver"),
("Bécquerver"),
("Becerraver"),
("Batistaver"),
("Batalver"),
("Bastidaver"),
("Bassolsver"),
("Barrosover"),
("Barretover"),
("Barredaver"),
("Barcelóver"),
("Barbierver"),
("Barberáver"),
("Barbadover"),
("Baquerover"),
("Banyulsver"),
("Bandrésver"),
("Bandamaver"),
("Balzover"),
("Balseraver"),
("Ballerover"),
("Bagaríaver"),
("Babianover"),
("Azpiazuver"),
("Azorerover"),
("Avidavever"),
("Areilzaver"),
("Arboleaver"),
("Araucoaver"),
("Arandiaver"),
("Aracielver"),
("Antúnezver"),
("Ansúrezver"),
("Anguitaver"),
("Anduezaver"),
("Andradever"),
("Andradaver"),
("Almuniaver"),
("Almeidaver"),
("Almarazver"),
("Almanzaver"),
("Almazánver"),
("Almansaver"),
("Almagrover"),
("Allendever"),
("Alemanyver"),
("Alegríaver"),
("Alcoleaver"),
("Alcocerver"),
("Alcarazver"),
("Albertover"),
("Alberdiver"),
("Albertiver"),
("Alberasver"),
("Arcónver"),
("Albénizver"),
("Anzónver"),
("Ajofrínver"),
("Ahumadaver"),
("Agustínver"),
("Aguirrever"),
("Aguirver"),
("Adelmónver"),
("Acevedover"),
("Aceínver"),
("Abrinesver"),
("Abellánver"),
("Abascalver"),
("Santiago"),
("Sanjurjover"),
("Saavedraver"),
("Rubialesver"),
("Rivellesver"),
("Ribellesver"),
("Quitueraver"),
("Quiñonesver"),
("Quinterover"),
("Quintanaver"),
("Olivaresver"),
("ODonojúver"),
("ODonellver"),
("Nogueiraver"),
("madridver"),
("Bandaver"),
("Kindelánver"),
("Guitarraver"),
("Guirartever"),
("Esquerdover"),
("Espinosaver"),
("Escuderover"),
("Esconover"),
("Escobedover"),
("Escaviasver"),
("Escalonaver"),
("Escadaver"),
("Entralgover"),
("Elizondover"),
("Elizaldever"),
("Elejaldever"),
("Egurbidever"),
("Echanovever"),
("Dorantesver"),
("Doménechver"),
("delClosver"),
("deArcasver"),
("Clementever"),
("Crianaver"),
("Cisnerosver"),
("Churrucaver"),
("Cifontesver"),
("Chávarriver"),
("Chamorrover"),
("Cervetosver"),
("Ceballosver"),
("Castillover"),
("Castellóver"),
("Castejónver"),
("Castañosver"),
("Castañerver"),
("Carvajalver"),
("Carrillover"),
("Carrerasver"),
("Carrascover"),
("Carranzaver"),
("Cárdenasver"),
("Carbaxalver"),
("Carballover"),
("Carbajalver"),
("Caparrósver"),
("Canilsver"),
("Campillover"),
("Caminerover"),
("Calderónver"),
("Caldeiraver"),
("Casanzver"),
("Cabralesver"),
("Busquetsver"),
("Burgueraver"),
("Brugueraver"),
("Bouffardver"),
("Borbolver"),
("Bonapartver"),
("Bellpuigver"),
("Bejaranover"),
("Becerrilver"),
("Beaumontver"),
("Bautistaver"),
("Bastardover"),
("Basconesver"),
("Bartomeuver"),
("Barrancover"),
("Barnuevover"),
("Barbaránver"),
("Barahonaver"),
("Baptistaver"),
("Balbuenaver"),
("Baguerver"),
("Azcáratever"),
("Arboleyaver"),
("Arboledaver"),
("Arbeizver"),
("Arbeláezver"),
("Aramburuver"),
("Bouffartver"),
("Aragonésver"),
("Apariciover"),
("Antuñanover"),
("Ansorenaver"),
("Anguianover"),
("Alvaradover"),
("Aimerichver"),
("Alicantever"),
("Alfonsínver"),
("Albornozver"),
("Albertínver"),
("Albacetever"),
("Ahajadasver"),
("Abainaver"),
("Agustinaver"),
("Aguinagaver"),
("Aguileraver"),
("Agramontver"),
("Agramuntver"),
("Agazonesver"),
("Afrontesver"),
("Acorelver"),
("Aceitunover"),
("Abráldezver"),
("Abengozaver"),
("Vahamonde"),
("Santiagover"),
("Sanjurjover"),
("Salgadover"),
("Romayver"),
("Saavedraver"),
("Riberaver"),
("Quirogaver"),
("Ocampover"),
("Novoaver"),
("Nogueiraver"),
("Neyraver"),
("Neiraver"),
("Lemosver"),
("Lemaver"),
("masver"),
("gover"),
("Goyanesver"),
("Godoyver"),
("Donisver"),
("Chacónver"),
("Ceaver"),
("Carballover"),
("Campanaver"),
("Calderaver"),
("Caldeiraver"),
("Cabreraver"),
("Borrajover"),
("Duránver"),
("Bellónver"),
("Becerraver"),
("Barrosover"),
("Barrantesver"),
("Barralver"),
("Bañosver"),
("Balboaver"),
("Bahamondever"),
("Avelnedaver"),
("Araújover"),
("Apontever"),
("Andradever"),
("Andradaver"),
("Aldanaver"),
("Agarver"),
("Aguiarver"),
("Adiónver"),
("Acevedover"),
("Aceijaver"),
("Abréuver"),
("Abráldezver"),
("Serna"),
("Santosver"),
("Sazarver"),
("Ruedaver"),
("Roblesver"),
("Roaver"),
("Rivasver"),
("Ribasver"),
("Ríosver"),
("Requenaver"),
("Redondover"),
("Olmover"),
("Olmedover"),
("Olivover"),
("Ojedaver"),
("Niñover"),
("Nietover"),
("Lermaver"),
("ver"),
("Ledesmaver"),
("Hermosilver"),
("Herasver"),
("Heraver"),
("Guirartever"),
("Guiraover"),
("Guiralver"),
("Giraldover"),
("Espinosaver"),
("Escuderover"),
("Escobedover"),
("Escobarver"),
("Escobalver"),
("Escamaver"),
("Escalonaver"),
("Escadaver"),
("Duerover"),
("Dueñasver"),
("Dorartever"),
("Dorantesver"),
("Dorantever"),
("Domingover"),
("Dobsver"),
("delCampover"),
("desHerasver"),
("deCerdaver"),
("deCastrover"),
("Cobosver"),
("Cobover"),
("Cisnerosver"),
("Cifuentesver"),
("Cifontesver"),
("Chicover"),
("Chamorrover"),
("Cerdaver"),
("Cepedaver"),
("Castrover"),
("Castresanaver"),
("Castelnosver"),
("Carvajalver"),
("Carriónver"),
("Carrillover"),
("Carrascover"),
("Carnicerover"),
("Carnerover"),
("Carbaxalver"),
("Carbajalver"),
("Camposver"),
("Cañasver"),
("Campoover"),
("Campover"),
("Campillover"),
("Caminerover"),
("Catravaver"),
("Calvover"),
("Cadenaver"),
("Cabezónver"),
("Cabezasver"),
("Cabellover"),
("Cabañasver"),
("Bustosver"),
("Bustover"),
("Bustover"),
("Buenover"),
("Burgosver"),
("Brotónver"),
("Bretónver"),
("Betrónver"),
("Becerrilver"),
("Basconesver"),
("Barrionuevover"),
("Barrientosver"),
("Barrancover"),
("Barraver"),
("Barnuevover"),
("Barcover"),
("Barbadover"),
("Barahonaver"),
("Ballesterosver"),
("Ballesterover"),
("Baldenachesver"),
("Bailénver"),
("Bacaraver"),
("Arandiaver"),
("Arandaver"),
("Antuñanover"),
("Antolínezver"),
("Ansúrezver"),
("Altamiranover"),
("Almazánver"),
("Almanzaver"),
("Aldehuever"),
("Almansaver"),
("Alcocerver"),
("Alcarazver"),
("Alcántaraver"),
("Albornozver"),
("Anzónver"),
("Ahumadaver"),
("Aguadover"),
("Ágredaver"),
("Agazonesver"),
("Aenllover"),
("Aenllever"),
("Aellosver"),
("Aellever"),
("Adamever"),
("Aceraver"),
("Acebesver");


drop table if exists paises;

create table paises(
id_pais int primary key auto_increment,
country varchar(200)
)engine=innodb;


/*LOAD DATA
LOCAL INFILE 'C:\\location.csv'
INTO TABLE datos
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';*/


insert into paises (country) values
("Afganistán")
,("Albania")
,("Alemania")
,("Andorra")
,("Angola")
,("Antigua y Barbuda")
,("Arabia Saudita")
,("Argelia")
,("Argentina")
,("Armenia")
,("Australia")
,("Austria")
,("Azerbaiyán")
,("Bahamas")
,("Bangladés")
,("Barbados")
,("Baréin")
,("Bélgica")
,("Belice")
,("Benín")
,("Bielorrusia")
,("Birmania")
,("Bolivia")
,("Bosnia y Herzegovina")
,("Botsuana")
,("Brasil")
,("Brunéi")
,("Bulgaria")
,("Burkina Faso")
,("Burundi")
,("Bután")
,("Cabo Verde")
,("Camboya")
,("Camerún")
,("Canadá")
,("Catar")
,("Chad")
,("Chile")
,("China")
,("Chipre")
,("Ciudad del Vaticano")
,("Colombia")
,("Comoras")
,("Corea del Norte")
,("Corea del Sur")
,("Costa de Marfil")
,("Costa Rica")
,("Croacia")
,("Cuba")
,("Dinamarca")
,("Dominica")
,("Ecuador")
,("Egipto")
,("El Salvador")
,("Emiratos Árabes Unidos")
,("Eritrea")
,("Eslovaquia")
,("Eslovenia")
,("España")
,("Estados Unidos")
,("Estonia")
,("Etiopía")
,("Filipinas")
,("Finlandia")
,("Fiyi")
,("Francia")
,("Gabón")
,("Gambia")
,("Georgia")
,("Ghana")
,("Granada")
,("Grecia")
,("Guatemala")
,("Guyana")
,("Guinea")
,("Guinea ecuatorial")
,("Guinea-Bisáu")
,("Haití")
,("Honduras")
,("Hungría")
,("India")
,("Indonesia")
,("Irak")
,("Irán")
,("Irlanda")
,("Islandia")
,("Islas Marshall")
,("Islas Salomón")
,("Israel")
,("Italia")
,("Jamaica")
,("Japón")
,("Jordania")
,("Kazajistán")
,("Kenia")
,("Kirguistán")
,("Kiribati")
,("Kuwait")
,("Laos")
,("Lesoto")
,("Letonia")
,("Líbano")
,("Liberia")
,("Libia")
,("Liechtenstein")
,("Lituania")
,("Luxemburgo")
,("Madagascar")
,("Malasia")
,("Malaui")
,("Maldivas")
,("Malí")
,("Malta")
,("Marruecos")
,("Mauricio")
,("Mauritania")
,("Micronesia")
,("Moldavia")
,("Mongolia")
,("Montenegro")
,("Mozambique")
,("Namibia")
,("Nauru")
,("Nepal")
,("Nicaragua")
,("Níger")
,("Nigeria")
,("Noruega")
,("Nueva Zelanda")
,("Omán")
,("Pakistán")
,("Palaos")
,("Panamá")
,("Papúa Nueva Guinea")
,("Paraguay")
,("Perú")
,("Polonia")
,("Portugal")
,("Reino Unido")
,("República Centroafricana")
,("República Checa")
,("República de Macedonia")
,("República del Congo")
,("República Democrática del Congo")
,("República Dominicana")
,("República Sudafricana")
,("Ruanda")
,("Rumanía")
,("Rusia")
,("Samoa")
,("San Cristóbal y Nieves")
,("San Marino")
,("San Vicente y las Granadinas")
,("Santa Lucía")
,("Senegal")
,("Serbia")
,("Seychelles")
,("Sierra Leona")
,("Singapur")
,("Siria")
,("Somalia")
,("Sri Lanka")
,("Suazilandia")
,("Sudán")
,("Sudán del Sur")
,("Suecia")
,("Suiza")
,("Surinam")
,("Tailandia")
,("Tanzania")
,("Tayikistán")
,("Timor Oriental")
,("Togo")
,("Tonga")
,("Trinidad y Tobago")
,("Túnez")
,("Turkmenistán")
,("Turquía")
,("Tuvalu")
,("Ucrania")
,("Uganda")
,("Uruguay")
,("Uzbekistán")
,("Vanuatu")
,("Venezuela")
,("Vietnam")
,("Yemen")
,("Yibuti")
,("Zambia")
,("Zimbabue");


drop table if exists municipio;

create table municipios(
id_municipio int primary key auto_increment,
municipio varchar(200)
)engine=innodb;


insert into municipios (municipio) values
("Marteo"),
("Concepción Pápalo"),
("Concepción Buenavista"),
("Coicoyán de las Flores"),
("Coatecas Altas"),
("Ciudad Ixtepec"),
("Ciénega de Zimatlán"),
("Chiquihuitlán de Benito Juárez"),
("Chalcatongo de Hidalgo"),
("Chahuites"),
("Capulálpam de Méndez"),
("Candelaria Loxicha"),
("Calihualá"),
("Ayoquezco de Aldama"),
("Ayotzintepec"),
("Asunción Tlacolulita"),
("Asunción Ocotlán"),
("Asunción Nochixtlán"),
("Asunción Ixtaltepec"),
("Asunción Cuyotepeji"),
("Asunción Cacalotepec"),
("Animas Trujano"),
("Acatlán de Pérez Figueroa"),
("Abejones"),
("Xochimilco"),
("Venustiano Carranza"),
("Tlalpan"),
("Tláhuac"),
("Milpa Alta"),
("Miguel Hidalgo"),
("La Magdalena Contreras"),
("Iztapalapa"),
("Iztacalco"),
("Gustavo A. Madero"),
("Cuauhtémoc"),
("Cuajimalpa de Morelos"),
("Coyoacán"),
("Benito Juárez"),
("Azcapotzalco"),
("Alvaro Obregón"),
("Valle de Zaragoza"),
("Uruachi"),
("Urique"),
("Temósachi"),
("Saucillo"),
("Satevó"),
("Santa Isabel"),
("Santa Bárbara"),
("San Francisco del Oro"),
("San Francisco de Conchos"),
("San Francisco de Borja"),
("Rosario"),
("Rosales"),
("Riva Palacio"),
("Praxedis G. Guerrero"),
("Ojinaga"),
("Ocampo"),
("Nuevo Casas Grandes"),
("Nonoava"),
("Namiquipa"),
("Moris"),
("Morelos"),
("Meoqui"),
("Matamoros"),
("Matachí"),
("Manuel Benavides"),
("Maguarichi"),
("Madera"),
("López"),
("La Cruz"),
("Julimes"),
("Juárez"),
("Janos"),
("Ignacio Zaragoza"),
("Jiménez"),
("Huejotitán"),
("Hidalgo del Parral"),
("Guerrero"),
("Guazapares"),
("Guadalupe y Calvo"),
("Guadalupe"),
("Guachochi"),
("Gran Morelos"),
("Gómez Farías"),
("El Tule"),
("Galeana"),
("Dr. Belisario Domínguez"),
("Cusihuiriachi"),
("Delicias"),
("Cuauhtémoc"),
("Coyame del Sotol"),
("Coronado"),
("Chínipas"),
("Chihuahua"),
("Casas Grandes"),
("Carichí"),
("Camargo"),
("Buenaventura"),
("Bocoyna"),
("Batopilas"),
("Balleza"),
("Bachíniva"),
("Ascensión"),
("Aquiles Serdán"),
("Allende"),
("Aldama"),
("Ahumada"),
("Zinacantán"),
("Yajalón"),
("Villaflores"),
("Villa Corzo"),
("Villa Comaltitlán"),
("Venustiano Carranza"),
("Unión Juárez"),
("Tzimol"),
("Tuzantán"),
("Tuxtla Gutiérrez"),
("Tuxtla Chico"),
("Tumbalá"),
("Totolapa"),
("Tonalá"),
("Tila"),
("Teopisca"),
("Tenejapa"),
("Tecpatán"),
("Tapilula"),
("Tapalapa"),
("Tapachula"),
("Sunuapa"),
("Suchiate"),
("Suchiapa"),
("Soyaló"),
("Solosuchiapa"),
("Socoltenango"),
("Sitalá"),
("Simojovel"),
("Siltepec"),
("Santiago el Pinar"),
("San Lucas"),
("San Juan Cancuc"),
("San Fernando"),
("San Andrés Duraznal"),
("San Cristóbal de las Casas"),
("Salto de Agua"),
("Sabanilla"),
("Reforma"),
("Rayón"),
("Pueblo Nuevo Solistahuacán"),
("Pijijiapan"),
("Pichucalco"),
("Pantepec"),
("Pantelhó"),
("Palenque"),
("Oxchuc"),
("Osumacinta"),
("Ostuacán"),
("Ocozocoautla de Espinosa"),
("Ocotepec"),
("Ocosingo"),
("Nicolás Ruíz"),
("Motozintla"),
("Montecristo de Guerrero"),
("Mitontic"),
("Metapa"),
("Mazatán"),
("Mazapa de Madero"),
("Marqués de Comillas"),
("Maravilla Tenejapa"),
("Mapastepec"),
("Las Rosas"),
("Las Margaritas"),
("Larráinzar"),
("La Libertad"),
("La Independencia"),
("La Grandeza"),
("La Concordia"),
("Juárez"),
("Jitotol"),
("Jiquipilas"),
("Ixtapangajoya"),
("Ixtapa"),
("Ixtacomitán"),
("Ixhuatán"),
("Huixtla"),
("Huixtán"),
("Huitiupán"),
("Huehuetán"),
("Frontera Hidalgo"),
("Frontera Comalapa"),
("Francisco León"),
("Escuintla"),
("El Porvenir"),
("El Bosque"),
("Copainalá"),
("Comitán de Domínguez"),
("Coapilla"),
("La Trinitaria"),
("Cintalapa"),
("Chilón"),
("Chicomuselo"),
("Chicoasén"),
("Chiapilla"),
("Chiapa de Corzo"),
("Cacahoatán"),
("Chenalhó"),
("Chapultenango"),
("Chanal"),
("Chamula"),
("Chalchihuitán"),
("Bochil"),
("Catazajá"),
("Berriozábal"),
("Benemérito de las Américas"),
("Bella Vista"),
("Arriaga"),
("Bejucal de Ocampo"),
("Angel Albino Corzo"),
("Amatenango del Valle"),
("Amatenango de la Frontera"),
("Amatán"),
("Altamirano"),
("Aldama"),
("Acapetahua"),
("Acala"),
("Acacoyagua"),
("Villa de Alvarez"),
("Minatitlán"),
("Tecomán"),
("Manzanillo"),
("Ixtlahuacán"),
("Cuauhtémoc"),
("Coquimatlán"),
("Comala"),
("Colima"),
("Armería"),
("Zaragoza"),
("Villa Unión"),
("Viesca"),
("Torreón"),
("Sierra Mojada"),
("San Pedro"),
("San Buenaventura"),
("Saltillo"),
("Sacramento"),
("Sabinas"),
("Ramos Arizpe"),
("Progreso"),
("Piedras Negras"),
("Parras"),
("Ocampo"),
("San Juan de Sabinas"),
("Nava"),
("Nadadores"),
("Múzquiz"),
("Morelos"),
("Monclova"),
("Matamoros"),
("Lamadrid"),
("Juárez"),
("Jiménez"),
("Hidalgo"),
("Guerrero"),
("General Cepeda"),
("Frontera"),
("Francisco I. Madero"),
("Cuatrociénegas"),
("Escobedo"),
("Castaños"),
("Candela"),
("Arteaga"),
("Allende"),
("Acuña"),
("Abasolo"),
("Zacatecas"),
("Villanueva"),
("Villa Hidalgo"),
("Villa González Ortega"),
("Villa García"),
("Villa de Cos"),
("Valparaíso"),
("Vetagrande"),
("Trinidad García de la Cadena"),
("Trancoso"),
("Tlaltenango de Sánchez Román"),
("Teul de González Ortega"),
("Tepetongo"),
("Tepechitlán"),
("Tabasco"),
("Susticacán"),
("Sombrerete"),
("Santa María de la Paz"),
("Sain Alto"),
("Río Grande"),
("Pinos"),
("Pánuco"),
("Ojocaliente"),
("Noria de ?ngeles"),
("Nochistlán de Mejía"),
("Moyahua de Estrada"),
("Morelos"),
("Monte Escobedo"),
("Momax"),
("Miguel Auza"),
("Mezquital del Oro"),
("Melchor Ocampo"),
("Mazapil"),
("Luis Moya"),
("Loreto"),
("Juchipila"),
("Juan Aldama"),
("Jiménez del Teul"),
("Jerez"),
("Jalpa"),
("Huanusco"),
("Guadalupe"),
("General Pánfilo Natera"),
("General Francisco R. Murguía"),
("General Enrique Estrada"),
("Genaro Codina"),
("Fresnillo"),
("El Salvador"),
("El Plateado de Joaquín Amaro"),
("Cuauhtémoc"),
("Concepción del Oro"),
("Chalchihuites"),
("Cañitas de Felipe Pescador"),
("Calera"),
("Benito Juárez"),
("Atolinga"),
("Apulco"),
("Apozol"),
("Zaragoza"),
("Villa Unión"),
("Viesca"),
("Torreón"),
("Sierra Mojada"),
("San Pedro"),
("San Juan de Sabinas"),
("Saltillo"),
("San Buenaventura"),
("Sacramento"),
("Sabinas"),
("Ramos Arizpe"),
("Progreso"),
("Parras"),
("Piedras Negras"),
("Ocampo"),
("Nava"),
("Nadadores"),
("Múzquiz"),
("Morelos"),
("Monclova"),
("Matamoros"),
("Lamadrid"),
("Jiménez"),
("Juárez"),
("Hidalgo"),
("Guerrero"),
("General Cepeda"),
("Frontera"),
("Francisco I. Madero"),
("Escobedo"),
("Cuatrociénegas"),
("Castaños"),
("Candela"),
("Arteaga"),
("Allende"),
("Acuña"),
("Abasolo"),
("Tenabo"),
("Palizada"),
("Hopelchén"),
("Hecelchakán"),
("Escárcega"),
("Champotón"),
("Carmen"),
("Candelaria"),
("Campeche"),
("Calkiní"),
("Calakmul"),
("Mulegé"),
("Los Cabos"),
("La Paz"),
("Loreto"),
("Comondú"),
("Tijuana"),
("Tecate"),
("Playas de Rosarito"),
("Mexicali"),
("Ensenada"),
("Tepezalá"),
("San José de Gracia"),
("San Francisco de los Romo"),
("Rincón de Romos"),
("Pabellón de Arteaga"),
("Jesús María"),
("El Llano"),
("Cosío"),
("Calvillo"),
("Asientos");
