drop database if exists GENERADORBD;
create database GENERADORBD;

use GENERADORBD;

drop table if exists informacion;

create table informacion(
id_info int primary key auto_increment,
nom_persona varchar(100),
ape_pat_persona varchar(100),
ape_mat_persona varchar(100)

)engine=innodb;



create table paises(
id_pais int primary key auto_increment,
nom_pais varchar(100)
)engine=innodb;


insert into paises (nom_pais) values
("Afganistán")
,("Albania")
,("Alemania")
,("Andorra")
,("Angola")
,("Antigua y Barbuda")
,("Arabia Saudita")
,("Argelia")
,("Argentina")
,("Armenia")
,("Australia")
,("Austria")
,("Azerbaiyán")
,("Bahamas")
,("Bangladés")
,("Barbados")
,("Baréin")
,("Bélgica")
,("Belice")
,("Benín")
,("Bielorrusia")
,("Birmania")
,("Bolivia")
,("Bosnia y Herzegovina")
,("Botsuana")
,("Brasil")
,("Brunéi")
,("Bulgaria")
,("Burkina Faso")
,("Burundi")
,("Bután")
,("Cabo Verde")
,("Camboya")
,("Camerún")
,("Canadá")
,("Catar")
,("Chad")
,("Chile")
,("China")
,("Chipre")
,("Ciudad del Vaticano")
,("Colombia")
,("Comoras")
,("Corea del Norte")
,("Corea del Sur")
,("Costa de Marfil")
,("Costa Rica")
,("Croacia")
,("Cuba")
,("Dinamarca")
,("Dominica")
,("Ecuador")
,("Egipto")
,("El Salvador")
,("Emiratos Árabes Unidos")
,("Eritrea")
,("Eslovaquia")
,("Eslovenia")
,("España")
,("Estados Unidos")
,("Estonia")
,("Etiopía")
,("Filipinas")
,("Finlandia")
,("Fiyi")
,("Francia")
,("Gabón")
,("Gambia")
,("Georgia")
,("Ghana")
,("Granada")
,("Grecia")
,("Guatemala")
,("Guyana")
,("Guinea")
,("Guinea ecuatorial")
,("Guinea-Bisáu")
,("Haití")
,("Honduras")
,("Hungría")
,("India")
,("Indonesia")
,("Irak")
,("Irán")
,("Irlanda")
,("Islandia")
,("Islas Marshall")
,("Islas Salomón")
,("Israel")
,("Italia")
,("Jamaica")
,("Japón")
,("Jordania")
,("Kazajistán")
,("Kenia")
,("Kirguistán")
,("Kiribati")
,("Kuwait")
,("Laos")
,("Lesoto")
,("Letonia")
,("Líbano")
,("Liberia")
,("Libia")
,("Liechtenstein")
,("Lituania")
,("Luxemburgo")
,("Madagascar")
,("Malasia")
,("Malaui")
,("Maldivas")
,("Malí")
,("Malta")
,("Marruecos")
,("Mauricio")
,("Mauritania")
,("Micronesia")
,("Moldavia")
,("Mongolia")
,("Montenegro")
,("Mozambique")
,("Namibia")
,("Nauru")
,("Nepal")
,("Nicaragua")
,("Níger")
,("Nigeria")
,("Noruega")
,("Nueva Zelanda")
,("Omán")
,("Pakistán")
,("Palaos")
,("Panamá")
,("Papúa Nueva Guinea")
,("Paraguay")
,("Perú")
,("Polonia")
,("Portugal")
,("Reino Unido")
,("República Centroafricana")
,("República Checa")
,("República de Macedonia")
,("República del Congo")
,("República Democrática del Congo")
,("República Dominicana")
,("República Sudafricana")
,("Ruanda")
,("Rumanía")
,("Rusia")
,("Samoa")
,("San Cristóbal y Nieves")
,("San Marino")
,("San Vicente y las Granadinas")
,("Santa Lucía")
,("Senegal")
,("Serbia")
,("Seychelles")
,("Sierra Leona")
,("Singapur")
,("Siria")
,("Somalia")
,("Sri Lanka")
,("Suazilandia")
,("Sudán")
,("Sudán del Sur")
,("Suecia")
,("Suiza")
,("Surinam")
,("Tailandia")
,("Tanzania")
,("Tayikistán")
,("Timor Oriental")
,("Togo")
,("Tonga")
,("Trinidad y Tobago")
,("Túnez")
,("Turkmenistán")
,("Turquía")
,("Tuvalu")
,("Ucrania")
,("Uganda")
,("Uruguay")
,("Uzbekistán")
,("Vanuatu")
,("Venezuela")
,("Vietnam")
,("Yemen")
,("Yibuti")
,("Zambia")
,("Zimbabue");